Repository hazelcast/hazelcast-simulator, pull requests merged in 2018-03, with the labels that each got.

#1670 Removed a directory upload from install-simulator.sh
  dist/src/main/dist/conf/install-simulator.sh
Labels: bug

#1667 Added --command option to worker-kill examples in README.md
  README.md
Labels: bug, documentation

#1680 Upgraded zulu 8 support to latest
  dist/src/main/dist/jdk-install/jdk-zulu-8-64.sh
Labels: enhancement

#1677 Upgraded zulu 7 to latest release fix #1676
  dist/src/main/dist/jdk-install/jdk-zulu-7-64.sh
Labels: enhancement

#1681 Added zulu 9 support
  dist/src/main/dist/conf/simulator.properties
  dist/src/main/dist/jdk-install/jdk-zulu-9-64.sh
Labels: enhancement

#1682 Added Zulu 10 support
  dist/src/main/dist/conf/simulator.properties
  dist/src/main/dist/jdk-install/jdk-zulu-10-64.sh
Labels: enhancement

#1685 Added OpenJDK 10 support
  dist/src/main/dist/conf/simulator.properties
  dist/src/main/dist/jdk-install/jdk-openjdk-10-64.sh
Labels: enhancement

#1686 Fixes the broken OpenJDK 8 installation
  dist/src/main/dist/jdk-install/jdk-openjdk-8-64.sh
Labels: bug

#1688 Upgraded Infinispan to 9.2.0-Final
  tests/tests-infinispan/pom.xml
  tests/tests-infinispan/src/main/java/com/hazelcast/simulator/infinispan/InfinispanDriver.java
Labels: task

#1690 Fixes an issue in the SimulatorHistogramLogProcessor
  simulator/src/main/java/com/hazelcast/simulator/utils/SimulatorHistogramLogProcessor.java
Labels: bug
