Repository hazelcast/hazelcast-simulator, pull requests merged in 2019-01, with the labels that each got.

#1727 Minor TestperformanceTracker simplification
  simulator/src/main/java/com/hazelcast/simulator/worker/performance/TestPerformanceTracker.java
Labels: cleanup

#1730 Maven repository update
  dist/src/main/dist/conf/install-hazelcast-enterprise.sh
Labels: enhancement

#1732 Fixes problem in performance.cvs.
  simulator/src/main/java/com/hazelcast/simulator/worker/performance/PerformanceLogWriter.java
Labels: bug
