Repository hazelcast/hazelcast-simulator, pull requests merged in 2020-01, with the labels that each got.

#1800 Fixed problem scaling down
  dist/src/main/dist/conf/aws-ec2_terminate.sh
  simulator/src/main/java/com/hazelcast/simulator/provisioner/Provisioner.java
Labels: bug

#1801 Upgraded AMI
  dist/src/main/dist/conf/simulator.properties
Labels: enhancement

#1803 Set global prepare to true for tests: IntIntMapTest and IntIntCacheTest
  tests/tests-hz/src/main/java/com/hazelcast/simulator/tests/icache/IntIntCacheTest.java
  tests/tests-hz/src/main/java/com/hazelcast/simulator/tests/map/IntIntMapTest.java
Labels: enhancement

#1804 Minor doc updates
  dist/src/main/dist/conf/aws-ec2_provision.sh
  dist/src/main/dist/conf/simulator.properties
Labels: cleanup, documentation

#1807 Fixes various report generator problems
  dist/src/main/dist/conf/init_report_files.sh
  pom.xml
  simulator/src/main/java/com/hazelcast/simulator/utils/HistogramTrimmer.java
  simulator/src/main/java/com/hazelcast/simulator/utils/ReportCsv.java
Labels: bug

#1809 Upgraded activemq to latest version
  dist/src/main/dist/conf/install-simulator.sh
  pom.xml
  simulator/pom.xml
Labels: enhancement

#1810 Minor dependency upgrades
  pom.xml
Labels: cleanup

#1811 Fixes CoordinatorTest
  archetype/src/main/resources/archetype-resources/workdir/client-hazelcast.xml
  simulator/src/test/resources/client-hazelcast.xml
Labels: bug

#1812 Fixes test failure SimulatorUtils
  simulator/src/main/java/com/hazelcast/simulator/utils/SimulatorUtils.java
  simulator/src/test/java/com/hazelcast/simulator/utils/SimulatorUtilsTest.java
Labels: bug, cleanup

#1813 Removed some old Jet dependencies
  dist/pom.xml
  dist/src/main/config/build-distribution-archive.xml
Labels: cleanup
