Repository hazelcast/hazelcast-simulator, pull requests merged in 2020-03, with the labels that each got.

#1845 Upgraded HZ 3 to 3.12.6
  drivers/driver-hazelcast3/pom.xml
Labels: enhancement

#1849 Removed IntIntCacheTest and IntIntMapTests
  drivers/driver-hazelcast4/src/main/java/com/hazelcast/simulator/tests/icache/IntIntCacheTest.java
  drivers/driver-hazelcast4/src/main/java/com/hazelcast/simulator/tests/map/IntIntMapTest.java
Labels: cleanup

#1852 Lettuce 5 cluster support
  checkstyle/suppressions.xml
  dist/pom.xml
  dist/src/main/config/build-distribution-archive.xml
  dist/src/main/dist/conf/simulator.properties
  drivers/driver-lettucecluster5/pom.xml
  drivers/driver-lettucecluster5/src/main/java/com/hazelcast/simulator/lettucecluster5/LettuceCluster5Driver.java
  drivers/driver-lettucecluster5/src/main/java/com/hazelcast/simulator/lettucecluster5/LettuceTest.java
  drivers/driver-lettucecluster5/src/main/java/com/hazelcast/simulator/lettucecluster5/sync/StringStringSyncTest.java
  drivers/pom.xml
Labels: enhancement

#1851 Fix starting dstat remotely
  dist/src/main/dist/conf/prepare_session.sh
Labels: bug

#1850 Fix typos in readme
  README.md
  simulator/src/main/resources/testSuite
Labels: cleanup, documentation

#1854 Upgraded machine to Nitro based and updated to latest Amazin Linux 2 AMI
  dist/src/main/dist/conf/simulator.properties
Labels: cleanup, enhancement

#1855 Added support for OpenJDK 14
  dist/src/main/dist/conf/simulator.properties
  dist/src/main/dist/jdk-install/jdk-openjdk-14-64.sh
Labels: enhancement

#1857 Added option for ec2 run-instances configuration
  dist/src/main/dist/conf/aws-ec2_provision.sh
  dist/src/main/dist/conf/simulator.properties
Labels: enhancement

#1858 Various ec2 cleanups
  dist/src/main/dist/conf/aws-ec2_provision.sh
  dist/src/main/dist/conf/simulator.properties
Labels: cleanup

#1859 HTML report generation
  dist/src/main/dist/conf/benchmark-report.py
Labels: enhancement
