Repository hazelcast/hazelcast-simulator, pull requests merged in 2023-10, with the labels that each got.

#2112 Reduced shutdown timeout
  conf/simulator.properties
  drivers/driver-infinispan10/conf/infinispan.xml
  drivers/driver-infinispan9/conf/infinispan.xml
Labels: enhancement

#2109 Templates upgraded to ubuntu 22.04 LTS
  templates/elasticache-cluster/inventory_plan.yaml
  templates/hazelcast5-ec2/inventory_plan.yaml
  templates/hazelcast5-hd-ec2/inventory_plan.yaml
  templates/sql-ec2/inventory_plan.yaml
  templates/sql-prunability-ec2/inventory_plan.yaml
  templates/storage-ec2/inventory_plan.yaml
Labels: cleanup

#2108 Templates are missing ec2 user
  templates/hazelcast5-ec2/inventory_plan.yaml
  templates/hazelcast5-hd-ec2/inventory_plan.yaml
  templates/storage-ec2/inventory_plan.yaml
Labels: cleanup

#2118 Handle negative elapsed time on HdrLatencyProbe.
  java/simulator/src/main/java/com/hazelcast/simulator/probes/LatencyProbe.java
  java/simulator/src/main/java/com/hazelcast/simulator/probes/impl/HdrLatencyProbe.java
  java/simulator/src/main/java/com/hazelcast/simulator/worker/Worker.java
  java/simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TestContainer.java
  java/simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TestContextImpl.java
  java/simulator/src/test/java/com/hazelcast/simulator/probes/impl/HdrLatencyProbeTest.java
Labels: bug

#2120 Fixed missing import
  java/simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TestContainer.java
Labels: bug

#2105 Upload drivers with rsync instead of scp
  src/simulator/ssh.py
  src/upload_hazelcast_jars.py
Labels: enhancement

#2124 inventory install simulator should include rsync
  playbooks/install_simulator.yaml
Labels: bug

#2128 Removed HistogramTrimmer
  java/simulator/src/main/java/com/hazelcast/simulator/utils/HistogramTrimmer.java
Labels: cleanup

#2131 Report generation: protection against non existing dirs.
  src/simulator/perftest_report_html.py
Labels: bug

#2141 Fix perf paranoid setting
  playbooks/install_perf.yaml
Labels: bug

#2142 Improved async_profiler doc
  performance_notes.txt
Labels: documentation

#2139 Minor performance output enhancement.
  java/simulator/src/main/java/com/hazelcast/simulator/coordinator/PerformanceStatsCollector.java
  java/simulator/src/test/java/com/hazelcast/simulator/coordinator/PerformanceStatsCollectorTest.java
Labels: enhancement

#2146 Fixes 'inventory destroy' when .terraform is missing.
  src/simulator/inventory_terraform.py
Labels: bug

#2148 Fix non existing dir handling report tool.
  src/simulator/perftest_report.py
Labels: bug

#2150 Java 9+ GC parameters update
  README.md
Labels: documentation

#2155 Added setup/teardown scripts
  templates/cp-ec2/setup
  templates/cp-ec2/teardown
  templates/elasticache-cluster/setup
  templates/elasticache-cluster/teardown
  templates/hazelcast5-ec2/setup
  templates/hazelcast5-ec2/teardown
  templates/hazelcast5-hd-ec2/setup
  templates/hazelcast5-hd-ec2/teardown
  templates/sql-ec2-tstore/setup
  templates/sql-ec2-tstore/teardown
  templates/sql-ec2/setup
  templates/sql-ec2/teardown
  templates/sql-prunability-ec2/setup
  templates/sql-prunability-ec2/teardown
  templates/storage-ec2/setup
  templates/storage-ec2/teardown
Labels: enhancement

#2158 Resolved 'perftest report -t' problem.
  src/simulator/perftest_report.py
Labels: bug

#2156 Fixes report generation utc problem.
  src/simulator/perftest_report_common.py
Labels: bug

#2154 Parallel broker connect.
  java/simulator/src/main/java/com/hazelcast/simulator/coordinator/Coordinator.java
Labels: enhancement

#2162 Perftest report default argument for output.
  src/simulator/perftest_report.py
Labels: cleanup

#2161 Protection unwanted report dir deletion.
  src/simulator/perftest_report.py
Labels: enhancement

#2160 Uses appropriate time unit in latency distribution per %
  src/simulator/perftest_report_common.py
  src/simulator/perftest_report_hdr.py
Labels: enhancement
