Repository hazelcast/hazelcast-simulator, pull requests merged in 2023-09, with the labels that each got.

#2041 Update README for Simulator 2.0
  README.md
  templates/hazelcast5-ec2/tests.yaml
Labels: cleanup, documentation

#2053 Supress Ansible python noise.
  templates/elasticache-cluster/ansible.cfg
  templates/hazelcast5-ec2/ansible.cfg
  templates/hazelcast5-hd-ec2/ansible.cfg
  templates/sql-ec2/ansible.cfg
  templates/sql-lab/ansible.cfg
  templates/storage-ec2/ansible.cfg
Labels: enhancement

#2047 Fix problem with TimeStepLoop logger.
  java/simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TimeStepLoop.java
Labels: bug

#2054 Added Ansible Python noise supression sql-prunability-ec2
  templates/sql-prunability-ec2/ansible.cfg
Labels: enhancement

#2056 Fixed problems with placement groups.
  templates/elasticache-cluster/aws/main.tf
  templates/elasticache-cluster/inventory_plan.yaml
  templates/hazelcast5-ec2/aws/main.tf
  templates/hazelcast5-ec2/inventory_plan.yaml
  templates/hazelcast5-hd-ec2/aws/main.tf
  templates/hazelcast5-hd-ec2/inventory_plan.yaml
  templates/sql-ec2-tstore/aws/main.tf
  templates/sql-ec2-tstore/inventory_plan.yaml
  templates/sql-ec2/aws/main.tf
  templates/sql-ec2/inventory_plan.yaml
  templates/sql-prunability-ec2/inventory_plan.yaml
  templates/storage-ec2/aws/main.tf
Labels: bug

#2040 Perftest run auto_gen_report flag addition & some bug fixes
  src/perftest_cli.py
  src/simulator/perftest.py
Labels: bug, enhancement, cleanup

#2075 Removed developers section from pom.
  java/pom.xml
Labels: enhancement

#2074 Bumped the maven plugins versions.
  java/drivers/driver-ignite2/pom.xml
  java/pom.xml
Labels: enhancement

#2072 Bumped the lettuce driver version
  java/drivers/driver-lettuce6/pom.xml
  java/drivers/driver-lettucecluster6/pom.xml
Labels: enhancement

#2065 Bumped the Ignite version to 2.15.0
  java/drivers/driver-ignite2/pom.xml
Labels: enhancement

#2063 Minor addition storage ec2 template README
  templates/storage-ec2/README.md
Labels: documentation

#2073 Ignored broken WorkerTest
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/utils/BuildInfoUtils.java
  java/simulator/src/test/java/com/hazelcast/simulator/worker/WorkerTest.java
Labels: bug

#2062 Added default --add-opens etc
  templates/hazelcast5-ec2/tests.yaml
  templates/hazelcast5-hd-ec2/tests.yaml
  templates/sql-ec2-tstore/tests.yaml
  templates/sql-ec2/tests-predicates.yaml
  templates/sql-ec2/tests-sql.yaml
  templates/sql-prunability-ec2/tests.yaml
  templates/storage-ec2/tests.yaml
Labels: enhancement

#2071 Bumped the mongo driver version
  java/drivers/driver-mongodb/pom.xml
Labels: enhancement

#2061 Updated to JDK 21
  src/inventory_cli.py
Labels: enhancement

#2069 Dropped infispan 9/10 support.
  java/drivers/driver-infinispan10/conf/infinispan.xml
  java/drivers/driver-infinispan10/pom.xml
  java/drivers/driver-infinispan10/src/main/java/com/hazelcast/simulator/infinispan10/Infinispan10Driver.java
  java/drivers/driver-infinispan10/src/main/java/com/hazelcast/simulator/infinispan10/InfinispanTest.java
  java/drivers/driver-infinispan10/src/main/java/com/hazelcast/simulator/infinispan10/cache/LongLongCacheTest.java
  java/drivers/driver-infinispan10/src/main/java/com/hazelcast/simulator/infinispan10/cache/LongStringCacheTest.java
  java/drivers/driver-infinispan10/src/main/resources/jgroups-tcp.xml
  java/drivers/driver-infinispan9/conf/infinispan.xml
  java/drivers/driver-infinispan9/pom.xml
  java/drivers/driver-infinispan9/src/main/java/com/hazelcast/simulator/infinispan9/Infinispan9Driver.java
  java/drivers/driver-infinispan9/src/main/java/com/hazelcast/simulator/infinispan9/InfinispanTest.java
  java/drivers/driver-infinispan9/src/main/java/com/hazelcast/simulator/infinispan9/cache/LongLongCacheTest.java
  java/drivers/driver-infinispan9/src/main/java/com/hazelcast/simulator/infinispan9/cache/LongStringCacheTest.java
  java/drivers/driver-infinispan9/src/main/resources/jgroups-tcp.xml
  java/drivers/pom.xml
  src/simulator/perftest.py
Labels: cleanup

#2080 Install either dstat or pcp
  playbooks/install_simulator.yaml
Labels: enhancement

#2086 Minor build cleanup
  build
Labels: cleanup

#2085 Cleaned up some ec2 templates
  templates/hazelcast5-ec2/hazelcast.xml
  templates/hazelcast5-ec2/tests.yaml
  templates/hazelcast5-hd-ec2/hazelcast.xml
  templates/hazelcast5-hd-ec2/tests.yaml
Labels: cleanup

#2090 hazelcast5-hd-ec2 unused instances
  templates/hazelcast5-hd-ec2/inventory_plan.yaml
  templates/hazelcast5-hd-ec2/tests.yaml
Labels: bug, cleanup

#2093 Removed unused simulator tests.
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/icache/StringICacheTest.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/jmx/PartitionServiceMBeanTest.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/BackupExpirationMapTest.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/ByteByteMapTest.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/IntByteMapTest.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/LongEmployeeMapTest.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/LongStringMapTest.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/MapAllValuesIdentifiedDataSerializableBenchmark.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/MapAsyncOpsTest.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/MapComplexPredicateTest.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/MapGetEntryIdentifiedDataSerializableBenchmark.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/MapLongPerformanceTest.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/MapPutAllOnTheFlyTest.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/MapPutAllTest.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/MapPutEntryIdentifiedDataSerializableBenchmark.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/MapRaceTest.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/MapSerializationTest.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/RegressionObject.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/SerializeRegressionTest.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/slow/SlowOperationMapTest.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/special/ClusterStatisticsTest.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/special/DummyTest.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/special/FailingTest.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/special/IterationTest.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/special/LongTestPhasesTest.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/special/helpers/InvocationTestClass.java
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/special/helpers/InvocationTestInterface.java
Labels: cleanup

#2095 Removed MapReduce functionality
  java/drivers/driver-hazelcast4plus/src/main/java/com/hazelcast/simulator/tests/map/helpers/MapReduceOperationCounter.java
Labels: cleanup

#2092 HdrProbe now tracks up to 24h of latency.
  java/simulator/src/main/java/com/hazelcast/simulator/probes/impl/HdrProbe.java
  java/simulator/src/test/java/com/hazelcast/simulator/probes/impl/HdrProbeTest.java
Labels: enhancement

#2096 Javadoc formatting.
  java/simulator/src/main/java/com/hazelcast/simulator/test/BaseThreadState.java
  java/simulator/src/main/java/com/hazelcast/simulator/test/StopException.java
  java/simulator/src/main/java/com/hazelcast/simulator/test/TestContext.java
  java/simulator/src/main/java/com/hazelcast/simulator/test/annotations/AfterRun.java
  java/simulator/src/main/java/com/hazelcast/simulator/test/annotations/BeforeRun.java
  java/simulator/src/main/java/com/hazelcast/simulator/test/annotations/InjectDriver.java
  java/simulator/src/main/java/com/hazelcast/simulator/test/annotations/InjectTestContext.java
  java/simulator/src/main/java/com/hazelcast/simulator/test/annotations/Prepare.java
  java/simulator/src/main/java/com/hazelcast/simulator/test/annotations/Run.java
  java/simulator/src/main/java/com/hazelcast/simulator/test/annotations/Setup.java
  java/simulator/src/main/java/com/hazelcast/simulator/test/annotations/StartNanos.java
  java/simulator/src/main/java/com/hazelcast/simulator/test/annotations/Teardown.java
  java/simulator/src/main/java/com/hazelcast/simulator/test/annotations/TimeStep.java
  java/simulator/src/main/java/com/hazelcast/simulator/test/annotations/Verify.java
Labels: cleanup

#2100 Probes exposed through TestContext.
  java/simulator/src/main/java/com/hazelcast/simulator/probes/Probe.java
  java/simulator/src/main/java/com/hazelcast/simulator/probes/impl/EmptyProbe.java
  java/simulator/src/main/java/com/hazelcast/simulator/probes/impl/HdrProbe.java
  java/simulator/src/main/java/com/hazelcast/simulator/test/TestContext.java
  java/simulator/src/main/java/com/hazelcast/simulator/worker/performance/TestPerformanceTracker.java
  java/simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/PropertyBinding.java
  java/simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TestContainer.java
  java/simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TestContextImpl.java
  java/simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TestManager.java
  java/simulator/src/main/java/com/hazelcast/simulator/worker/testcontainer/TimeStepLoop.java
  java/simulator/src/test/java/com/hazelcast/simulator/probes/impl/EmptyProbeTest.java
  java/simulator/src/test/java/com/hazelcast/simulator/probes/impl/HdrProbeTest.java
  java/simulator/src/test/java/com/hazelcast/simulator/worker/testcontainer/TestContainer_BasicTest.java
Labels: enhancement

#2084 Improved README.md: added performance testing section.
  README.md
Labels: enhancement, documentation
